apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pv-claim
  namespace: logging
  labels:
    app: elk
spec:
  storageClassName: rook-block 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
