apiVersion: v1
kind: Service
metadata:
  labels:
    app: elk
    stack: elk
  name: elk-public
  namespace: logging
spec:
  ports:
  - name: tcp-kibana 
    nodePort: 32658
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    stack: elk
  sessionAffinity: None
  type: NodePort
