apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: elk
  template:
    metadata:
      labels:
        app: elk
        stack: elk
    spec:
      containers:
      - name: elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: elk-persistent-storage
          mountPath: /elasticsearch/data
        - name: elk-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.2.2
        ports:
        - containerPort: 5601
        env:
          - name: ELASTICSEARCH_URL
            value: "http://localhost:9200"
      - name: logstash
        image: docker.elastic.co/logstash/logstash-oss:6.2.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      securityContext: 
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: elk-persistent-storage
        persistentVolumeClaim:
          claimName: elk-pv-claim
      - name: elk-config
        configMap:
          name: elasticsearch-config
      - name: logstash-config
        configMap:
          name: logstash-config
