apiVersion: v1 
kind: Namespace 
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: {{ template "elk.name" . }}
    chart: {{ template "elk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
