apiVersion: v1
kind: Service
metadata:
  name: elk 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "elk.name" . }}
    chart: {{ template "elk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP 
  ports:
    - name: elastic-tcp
      port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
      protocol: TCP
    - name: logstash-tcp
      port: {{ .Values.logstash.port }}
      targetPort: {{ .Values.logstash.port }}
      protocol: TCP
    - name: kibana-tcp
      port: {{ .Values.kibana.port }}
      targetPort: {{ .Values.kibana.port }}
      protocol: TCP
  selector:
    app: {{ template "elk.name" . }}
    release: {{ .Release.Name }}
