apiVersion: v1
kind: Service
metadata:
  name: logstash 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "elk.name" . }}
    chart: {{ template "elk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort 
  ports:
    - name: logstash-tcp
      port: {{ .Values.logstash.port }}
      targetPort: {{ .Values.logstash.port }}
      nodePort: {{ .Values.logstash.nodeport }}
      protocol: TCP
  selector:
    app: {{ template "elk.name" . }}
    release: {{ .Release.Name }}
